import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { registerEscrow, getEscrow } from '../services/escrowService';
import { registerPoller } from '../services/verifierService';
import { writeLimiter, readLimiter } from '../middleware/rateLimiter';
import { requireApiKey } from '../middleware/apiKey';
import { KroxySDK } from '@kroxy/sdk';

const router = Router();

// ─── Validation Schemas ───────────────────────────────────────────────────────

const ConditionSchema = z.object({
  type: z.enum(['http_status', 'json_field', 'latency_ms', 'uptime_percent']),
  endpoint: z.string().url('condition endpoint must be a valid URL'),
  field: z.string().optional(),
  operator: z.enum(['eq', 'gte', 'lte', 'contains']),
  expected: z.union([z.string(), z.number(), z.boolean()]),
});

const ConditionsDefinitionSchema = z.object({
  version: z.literal('1.0'),
  escrowId: z.string().min(1),
  conditions: z.array(ConditionSchema).min(1, 'At least one condition is required'),
  windowSeconds: z.number().int().positive(),
  checkIntervalSeconds: z.number().int().positive(),
  requiredPassRate: z.number().min(0).max(1),
});

const EthAddressSchema = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/, 'Must be a valid Ethereum address (0x + 40 hex chars)');

const RegisterEscrowSchema = z.object({
  escrowId: z
    .string()
    .regex(/^0x[0-9a-fA-F]{64}$/, 'escrowId must be a 32-byte hex string (0x + 64 chars)'),
  payerAddress: EthAddressSchema,
  payeeAddress: EthAddressSchema,
  amountUsdc: z.number().positive('amountUsdc must be > 0'),
  conditionsJson: ConditionsDefinitionSchema,
  conditionsHash: z
    .string()
    .regex(/^0x[0-9a-fA-F]{64}$/, 'conditionsHash must be a bytes32 hex string'),
  x402Reference: z.string().min(1),
  escrowDurationSeconds: z.number().int().positive(),
  txHash: z
    .string()
    .regex(/^0x[0-9a-fA-F]{64}$/, 'txHash must be a valid transaction hash'),
  blockNumber: z.number().int().nonnegative(),
});

// Looser conditions schema for /create: escrowId is generated by the SDK,
// so callers pass an empty string and the SDK fills it in.
const CreateEscrowConditionsSchema = ConditionsDefinitionSchema.extend({
  escrowId: z.string().default(''),
});

const CreateEscrowSchema = z.object({
  payerPrivateKey: z.string().min(1),
  payeeAddress: EthAddressSchema,
  amountUsdc: z.number().positive(),
  conditions: CreateEscrowConditionsSchema,
  x402Reference: z.string().min(1),
});

// ─── Routes ───────────────────────────────────────────────────────────────────

// POST /api/escrows/create — create an escrow on-chain via KroxySDK (used by MCP tools).
// Unlike POST /api/escrows (which registers an already-settled escrow), this route
// signs and submits the on-chain transaction using the payer's private key.
router.post('/create', requireApiKey, writeLimiter, async (req: Request, res: Response) => {
  const parse = CreateEscrowSchema.safeParse(req.body);
  if (!parse.success) {
    res.status(400).json({ error: 'Validation failed', issues: parse.error.issues.map((i) => ({ path: i.path.join('.'), message: i.message })) });
    return;
  }
  const { payerPrivateKey, payeeAddress, amountUsdc, conditions, x402Reference } = parse.data;
  try {
    const sdk = new KroxySDK();
    const result = await sdk.createEscrow({ payerPrivateKey, payeeAddress, amountUsdc, conditions, x402Reference });
    res.status(201).json(result);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/', requireApiKey, writeLimiter, async (req: Request, res: Response) => {
  const parse = RegisterEscrowSchema.safeParse(req.body);
  if (!parse.success) {
    res.status(400).json({
      error: 'Validation failed',
      issues: parse.error.issues.map((i) => ({ path: i.path.join('.'), message: i.message })),
    });
    return;
  }

  const body = parse.data;

  // Extra guard: payer and payee must be different addresses
  if (body.payerAddress.toLowerCase() === body.payeeAddress.toLowerCase()) {
    res.status(400).json({ error: 'payerAddress and payeeAddress must be different' });
    return;
  }

  await registerEscrow(body);

  const expiresAt = new Date(Date.now() + body.escrowDurationSeconds * 1000);
  registerPoller(
    body.escrowId,
    body.conditionsJson,
    expiresAt,
    body.payeeAddress,
    BigInt(Math.round(body.amountUsdc * 1_000_000))
  );

  res.status(201).json({ escrowId: body.escrowId, registered: true });
});

router.get('/:escrowId', readLimiter, async (req: Request, res: Response) => {
  const escrow = await getEscrow(req.params.escrowId as string);
  if (!escrow) {
    res.status(404).json({ error: 'Escrow not found' });
    return;
  }
  res.json(escrow);
});

export default router;
